// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/template_project_version.test.ts.

/** The version of the `@tssuite/template-project` package. */
export const templateProjectVersion = '0.0.19';
